name: Build and Deploy Blog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Astro check
        run: npx astro check

      - name: Build Astro site
        run: npm run build
        env:
          NODE_ENV: production

      # --- SSH ---
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Ensure SSH secret is present
        run: |
          test -n "${{ secrets.SSH_PRIVATE_KEY }}" || (echo "SSH_PRIVATE_KEY is empty" && exit 1)

      # --- Deploy ---
      - name: Deploy to server
        run: |
          rsync -az --delete \
            --exclude='.htaccess' \
            --exclude='error_log' \
            --exclude='logs/' \
            --exclude='wp/' \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            dist/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/nico.ar-dist/"
